--liquibase formatted SQL

--changeset gavin:1
DROP TABLE IF EXISTS `PAYMENT`;
CREATE TABLE `PAYMENT` (
  `ID`            CHAR(36)       NOT NULL,
  `USER_ID`       CHAR(36)       NOT NULL,
  `ORDER_ID`      CHAR(36)                DEFAULT NULL,
  `AMOUNT`        DECIMAL(10, 0) NOT NULL,
  `STATUS`        VARCHAR(20)    NOT NULL,
  `VERSION`       BIGINT(20)              DEFAULT NULL,
  `CREATED_TIME`  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TIME` TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PAYMENT_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;