--liquibase formatted sql

--changeset gavin:1
DROP TABLE IF EXISTS `CARRIER`;
CREATE TABLE `CARRIER` (
  `ID`   CHAR(3)     NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CARRIER_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `DELIVERY`;
CREATE TABLE `DELIVERY` (
  `ID`              CHAR(36)     NOT NULL,
  `ORDER_ID`        CHAR(36)     NOT NULL,
  `CONSIGNEE`       VARCHAR(45)  NOT NULL,
  `ADDRESS`         VARCHAR(100) NOT NULL,
  `PHONE_NUMBER`    VARCHAR(20)  NOT NULL,
  `CARRIER_ID`      CHAR(3)               DEFAULT NULL,
  `TRACKING_NUMBER` VARCHAR(15)           DEFAULT NULL,
  `STATUS`          VARCHAR(20)  NOT NULL,
  `VERSION`         BIGINT(20)            DEFAULT NULL,
  `CREATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TIME`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DELIVERY_ID_UINDEX` (`ID`),
  KEY `DELIVERY_CARRIER_ID_FK` (`CARRIER_ID`),
  CONSTRAINT `DELIVERY_CARRIER_ID_FK` FOREIGN KEY (`CARRIER_ID`) REFERENCES `CARRIER` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

--changeset gavin:2
INSERT INTO CARRIER (ID, NAME) VALUES ('001', 'EMS');
INSERT INTO CARRIER (ID, NAME) VALUES ('002', 'UPS');