CREATE DATABASE IF NOT EXISTS `SCHEMA_ADDRESS`;
USE `SCHEMA_ADDRESS`;

DROP TABLE IF EXISTS `COUNTRY`;
CREATE TABLE `COUNTRY` (
  `ID`   CHAR(3)     NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COUNTRY_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `PROVINCE`;
CREATE TABLE `PROVINCE` (
  `ID`         CHAR(10)    NOT NULL,
  `NAME`       VARCHAR(45) NOT NULL,
  `COUNTRY_ID` CHAR(3)     NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVINCE_ID_UINDEX` (`ID`),
  KEY `PROVINCE_COUNTRY_ID_FK` (`COUNTRY_ID`),
  CONSTRAINT `PROVINCE_COUNTRY_ID_FK` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `CITY`;
CREATE TABLE `CITY` (
  `ID`          CHAR(10) NOT NULL,
  `NAME`        VARCHAR(45) DEFAULT NULL,
  `PROVINCE_ID` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CITY_ID_UINDEX` (`ID`),
  KEY `CITY_PROVINCE_ID_FK` (`PROVINCE_ID`),
  CONSTRAINT `CITY_PROVINCE_ID_FK` FOREIGN KEY (`PROVINCE_ID`) REFERENCES `PROVINCE` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `DISTRICT`;
CREATE TABLE `DISTRICT` (
  `ID`      CHAR(10)    NOT NULL,
  `NAME`    VARCHAR(45) NOT NULL,
  `CITY_ID` CHAR(10)    NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DISTRICT_ID_UINDEX` (`ID`),
  KEY `DISTRICT_CITY_ID_FK` (`CITY_ID`),
  CONSTRAINT `DISTRICT_CITY_ID_FK` FOREIGN KEY (`CITY_ID`) REFERENCES `CITY` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `ADDRESS`;
CREATE TABLE `ADDRESS` (
  `ID`           CHAR(36)    NOT NULL,
  `USER_ID`      CHAR(36)    NOT NULL,
  `CONSIGNEE`    VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` VARCHAR(20) NOT NULL,
  `DISTRICT_ID`  CHAR(10)    NOT NULL,
  `ZIP_CODE`     VARCHAR(10) NOT NULL,
  `STREET`       VARCHAR(45) NOT NULL,
  `BUILDING`     VARCHAR(45) NOT NULL,
  `ROOM`         VARCHAR(45) NOT NULL,
  `DEFAULT_FLAG` TINYINT(1)  NOT NULL,
  `COMMENT`      VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ADDRESS_ID_UINDEX` (`ID`),
  KEY `ADDRESS_DISTRICT_ID_FK` (`DISTRICT_ID`),
  CONSTRAINT `ADDRESS_DISTRICT_ID_FK` FOREIGN KEY (`DISTRICT_ID`) REFERENCES `DISTRICT` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

INSERT INTO SCHEMA_ADDRESS.COUNTRY (ID, NAME) VALUES ('001', '中国');

INSERT INTO SCHEMA_ADDRESS.PROVINCE (ID, NAME, COUNTRY_ID) VALUES ('0010000001', '上海市', '001');
INSERT INTO SCHEMA_ADDRESS.PROVINCE (ID, NAME, COUNTRY_ID) VALUES ('0010000002', '浙江省', '001');
INSERT INTO SCHEMA_ADDRESS.PROVINCE (ID, NAME, COUNTRY_ID) VALUES ('0010000003', '江苏省', '001');

INSERT INTO SCHEMA_ADDRESS.CITY (ID, NAME, PROVINCE_ID) VALUES ('0010020001', '杭州市', '0010000002');
INSERT INTO SCHEMA_ADDRESS.CITY (ID, NAME, PROVINCE_ID) VALUES ('0010020002', '舟山市', '0010000002');

INSERT INTO SCHEMA_ADDRESS.DISTRICT (ID, NAME, CITY_ID) VALUES ('0010020101', '西湖区', '0010020001');
INSERT INTO SCHEMA_ADDRESS.DISTRICT (ID, NAME, CITY_ID) VALUES ('0010020102', '上城区', '0010020001');
INSERT INTO SCHEMA_ADDRESS.DISTRICT (ID, NAME, CITY_ID) VALUES ('0010020103', '下城区', '0010020001');

INSERT INTO SCHEMA_ADDRESS.ADDRESS (ID, USER_ID, CONSIGNEE, PHONE_NUMBER, DISTRICT_ID, ZIP_CODE, STREET, BUILDING, ROOM, DEFAULT_FLAG, COMMENT)
VALUES ('f7a3559f-17aa-4cad-8876-4291c382a141', '806f0ac6-a3e4-42a1-8dfc-1a3e56002881', 'Gavin Guo', '13621670031',
                                                '0010020101', '201203', '文三路100号', '阿里巴巴大楼', '801', 0, '办公地址');