CREATE DATABASE IF NOT EXISTS `SCHEMA_PRODUCT`;
USE `SCHEMA_PRODUCT`;

DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE `CATEGORY` (
  `ID`        CHAR(6)     NOT NULL,
  `NAME`      VARCHAR(45) NOT NULL,
  `PARENT_ID` CHAR(6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CATEGORY_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `PRODUCT`;
CREATE TABLE `PRODUCT` (
  `ID`            CHAR(36)     NOT NULL,
  `NAME`          VARCHAR(100) NOT NULL,
  `CATEGORY_ID`   CHAR(6)      NOT NULL,
  `PRICE`         FLOAT        NOT NULL,
  `STOCKS`        INT(10)      NOT NULL,
  `COMMENT`       VARCHAR(200)          DEFAULT NULL,
  `VERSION`       BIGINT(20)            DEFAULT NULL,
  `CREATED_TIME`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TIME` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `CATEGORY_ID_FK_IDX` (`CATEGORY_ID`),
  CONSTRAINT `PRODUCT_CATEGORY_ID_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `POINT_REWARD_PLAN`;
CREATE TABLE `POINT_REWARD_PLAN` (
  `ID`           CHAR(36)  NOT NULL,
  `PRODUCT_ID`   CHAR(36)  NOT NULL,
  `RATIO`        FLOAT     NOT NULL,
  `START_DATE`   CHAR(10)  NOT NULL,
  `END_DATE`     CHAR(10)  NOT NULL,
  `VERSION`      BIGINT(20)         DEFAULT NULL,
  `CREATED_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `POINT_REWARD_PLAN_ID_UINDEX` (`ID`),
  KEY `POINT_REWARD_PLAN_PRODUCT_ID_FK` (`PRODUCT_ID`),
  CONSTRAINT `POINT_REWARD_PLAN_PRODUCT_ID_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `PRODUCT_RESERVATION`;
CREATE TABLE `PRODUCT_RESERVATION` (
  `ID`           CHAR(36)  NOT NULL,
  `PRODUCT_ID`   CHAR(36)  NOT NULL,
  `ORDER_ID`     CHAR(36)  NOT NULL,
  `QUANTITY`     INT(10)   NOT NULL,
  `VERSION`      BIGINT(20)         DEFAULT NULL,
  `CREATED_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PRODUCT_RESERVATION_ID_UINDEX` (`ID`),
  KEY `PRODUCT_RESERVATION_PRODUCT_ID_FK` (`PRODUCT_ID`),
  CONSTRAINT `PRODUCT_RESERVATION_PRODUCT_ID_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `CANCEL_RESERVATION_EVENT`;
CREATE TABLE `CANCEL_RESERVATION_EVENT` (
  `ID`            CHAR(36)    NOT NULL,
  `ORIGIN_ID`     CHAR(36)             DEFAULT NULL,
  `ORDER_ID`      CHAR(36)    NOT NULL,
  `STATUS`        VARCHAR(20) NOT NULL,
  `CREATED_TIME`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TIME` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CANCEL_RESERVATION_EVENT_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('A00001', 'Men''s	Clothing', NULL);
INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('A00002', 'Women''s	Clothing', NULL);

INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B01001', 'Clothing', 'A00001');
INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B01002', 'Shoes', 'A00001');
INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B01003', 'Accessories', 'A00001');

INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B02001', 'Clothing', 'A00002');
INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B02002', 'Shoes', 'A00002');
INSERT INTO SCHEMA_PRODUCT.CATEGORY (ID, NAME, PARENT_ID) VALUES ('B02003', 'Accessories', 'A00002');

INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('0e5b6fbd-8b6d-43e1-9c7b-ed4c00f319a9', 'Tommy Hilfiger Men''s Barnes Single Breasted Walker Coat', 'B01001', 149,
   1000, '70% Wool/20% Nylon/10% Cashmere', '2016-10-30 02:08:22',
   '2016-11-13 04:33:06');
INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('181c105f-1fa3-44c7-9793-090a19a6c897', 'Nautica Men''s 3 Button Wool Blend 37 Inch Topcoat', 'B01001', 60.5, 1000,
   '', '2016-10-30 01:56:52',
   '2016-10-30 01:56:52');
INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('545524a6-c3ec-47f2-9423-f4ee2f9959f0', 'New Balance Men''s ME541V1 Running Shoes', 'B01002', 53.9, 1000,
   'Textile and synthetic', '2016-10-30 02:09:56',
   '2016-11-12 06:42:39');
INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('668f3eac-b7cc-4a66-9012-48cb09ea0fea', 'Dexter Team Bowling Shoes', 'B01002', 42, 1000,
   'Soft, durable man-made upper',
   '2016-10-30 01:18:05', '2016-11-12 06:42:37');
INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('7395260f-41a7-44a1-bfc8-ae1c23f8afdc', 'Carhartt Men''s Acrylic Watch Hat A18', 'B01003', 9, 2000,
   '',
   '2016-10-30 07:33:03', '2016-11-12 06:42:34');
INSERT INTO SCHEMA_PRODUCT.PRODUCT (ID, NAME, CATEGORY_ID, PRICE, STOCKS, COMMENT, CREATED_TIME, MODIFIED_TIME) VALUES
  ('cb4d3cff-df04-4558-b22a-2f8941711121', 'Timberland Men''s Magic Glove with Touchscreen Technology', 'B01003', 6,
   2000, 'Solid knit glove with three-finger touchscreen conductivity',
   '2016-10-30 07:37:31', '2016-10-30 08:32:03');
