DROP DATABASE SCHEMA_AUTH;
CREATE DATABASE `SCHEMA_AUTH`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_USER;
CREATE DATABASE `SCHEMA_USER`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_ADDRESS;
CREATE DATABASE `SCHEMA_ADDRESS`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_POINT;
CREATE DATABASE `SCHEMA_POINT`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_PRODUCT;
CREATE DATABASE `SCHEMA_PRODUCT`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_ORDER;
CREATE DATABASE `SCHEMA_ORDER`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_PAYMENT;
CREATE DATABASE `SCHEMA_PAYMENT`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_DELIVERY;
CREATE DATABASE `SCHEMA_DELIVERY`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';

DROP DATABASE SCHEMA_NOTIFICATION;
CREATE DATABASE `SCHEMA_NOTIFICATION`
  CHARACTER SET 'utf8'
  COLLATE 'utf8_general_ci';