CREATE DATABASE IF NOT EXISTS `SCHEMA_NOTIFICATION`;
USE `SCHEMA_NOTIFICATION`;

DROP TABLE IF EXISTS `USER_CREATED_EVENT`;
CREATE TABLE `USER_CREATED_EVENT` (
  `ID`            CHAR(36)    NOT NULL,
  `ORIGIN_ID`     CHAR(36)             DEFAULT NULL,
  `USER_ID`       CHAR(36)    NOT NULL,
  `LOGIN_NAME`    VARCHAR(45) NOT NULL,
  `NICK_NAME`     VARCHAR(45) NOT NULL,
  `EMAIL`         VARCHAR(45) NOT NULL,
  `PHONE`         VARCHAR(45)          DEFAULT NULL,
  `STATUS`        VARCHAR(20) NOT NULL,
  `CREATED_TIME`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TIME` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_CREATED_EVENT_ID_UINDEX` (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;